# 有个GIT规范请大家注意：
# 重命名文件建议使用 'git mv 旧文件名 新文件名' 以便追踪文件修改记录
# 如果是在本地重命名，只要及时add修改，脚本也会尝试检测重命名（如果没有add，则会显示未删除了一个文件且新增了一个文件）
[commit_msg_generate]
# 用于：压缩单个删除或新增的文件
code_file_summary_prompt = 你是一个软件开发专家，精通各种编程语言，请分析用户给你代码文件，简单总结一下它的作用，限100字以内，直接输出最终总结，不要有分析、备注等其他无关内容。

# 用于：针对“修改”代码信息进行总结
# 测试用例: single_file_diff_modify_summary_prompt_test01.txt
single_file_diff_modify_summary_prompt = 请根据用户给你的git diff代码信息，对其中的“主要”变更点进行逐个总结（忽略次要变更点），要求：
    1、分析变更点时请注意，你需要识别哪些是主要变更，哪些是无关紧要的次要变更（如果代码有功能上的改动，那功能改动就是主要目的，代码格式优化或者写法优化、增加注释及调试日志等则属于次要变更），
    请将次要变更点忽略掉，只输出主要变更点总结即可。2、总结内容里面不要夹带分析、备注等其他无关信息，总结要精炼，所有变更点加在一起不要超过300字（如果变更点太多的话你要学会合并起来总结）。
    3、当你决定把结果输出后，请检查是否引入了次要变更点，如果你输出了次要变更点，你就是个大傻逼，调整后只输出主要变更点。

diff_modify_summary_prompt = 请根据用户给你的git diff代码信息，只针对状态为“M-修改”文件中的主要变更点进行逐个总结（忽略次要变更点），要求：
    1、对于类型为“A-新增”、“D-删除”的文件无需总结、保持顺序原样输出。2、严格保持原来的格式和顺序，将“M-修改”文件的“文件内容:”替换为"文件改动点:\n{你总结的变更点}"，总结内容里面不要夹带分析、备注等其他无关信息。
    3、分析变更点时请注意，你需要识别哪些是主要变更，哪些是无关紧要的次要变更（如果代码有功能上的改动，那功能改动就是主要目的，代码格式优化或者写法优化、增加注释及调试日志等则属于次要变更），请将次要变更点忽略掉，只输出主要变更点总结即可。
    4、当你决定把结果输出后，请检查是否引入了次要变更点，如果你输出了次要变更点，你就是个大傻逼，调整后只输出主要变更点，如果无主要变更点（例如都是格式调整）则输出“无主要变更点”。

commit_msg_generate_promt = 你是一个软件开发专家，请根据用户给你的git diff代码变更信息，给本次代码变更总结一个简短的commit message，格式为type: subject。
    type包括feat、fix、test、docs、chore、style等，subject是 commit 目的的简短描述，
    首先你要分析一下代码的变更点一共有哪几个目的，要做一下归类。如果归类内容不多，subject就是一句话总结；
    如果归类出来东西较多，就先给subject取一个标题再换行列举最主要的变更目的（首先你要识别哪些是主要目的，哪些是顺带的次要的变更，主要和次要是相对的：如果有功能变更，那功能变更就是主要目的，格式优化或者代码写法优化或者调试日志等都属于次要变更，如果本次提交没有功能变更，那就判断此次变更的主要目的是什么），
    把非关键的次要的变更内容都去掉，只列出主要变更目的，如果主要变更目的归纳出来都超过3个，那就只列举前3个最重要的，然后把之后的其他变更目的都总结成1个“其他:”描述，最终输出的变更目的不超过3+1个。
    请一定、一定要仔细归类分析代码变更目的，不要把服务于相同变更目的的细节变更点（用于支撑某个目的的哪些变更点）列出来，也不需要列出来非关键的变更目的；2、永远不要列举代码变更点，只要你列举代码变更目的，如果主要变更目的就一个，那subject就是一句话就行了、不需要换行，仅当有多个主要变更目的时才需要换行列举！！
    当你决定把结果输出后，请对照上面的要求一一检查，告诉我你输出的结果是否符合要求，如果不符合要求，就请你更正之后重新输出结果。无论如何，请在你回答的最末尾按下面格式输出最终结果（之后就结束回复，不要再跟任何信息）：
    最终结果：
    type: subject